version: "3.8"

services:
  db:
    build: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
    networks:
      - postgres
  app:
    build: ./app
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:
