version: '3'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /private/var/lib/postgresql:/var/lib/postgresql
    networks:
      - postgres
    expose:
      - 5432
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
  app:
    build: ./app
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - postgres
networks:
  postgres:
